// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhphmlqvikzdazvbrnbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFocGhtbHF2aWt6ZGF6dmJybmJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTk3NDcsImV4cCI6MjA2NTY3NTc0N30.Zl7bWYyXkmq3Lrj8LA8hVCptVl0V8fpBEcoSWP9JHyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);